<?php

namespace App\Http\Requests\Api\Sync;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

/**
 * Validates the payload the Flutter `SyncApiService.pushChanges` sends.
 *
 * Each entity is optional — clients push only the buckets they have
 * pending changes for. Within each bucket, each row must carry a
 * `clientId` (UUID generated by the device), an `updatedAt` (the
 * device's last-write timestamp, used for last-write-wins), and either
 * a `deletedAt` (for deletions) or the entity-specific payload fields.
 */
class PushRequest extends FormRequest
{
    public function authorize(): bool
    {
        return $this->user() !== null;
    }

    /**
     * @return array<string, mixed>
     */
    public function rules(): array
    {
        return [
            'transactions' => ['nullable', 'array'],
            'transactions.*.clientId' => ['required', 'uuid'],
            'transactions.*.updatedAt' => ['required', 'date'],
            'transactions.*.deletedAt' => ['nullable', 'date'],
            'transactions.*.amount' => ['nullable', 'numeric', 'min:0'],
            'transactions.*.type' => ['nullable', Rule::in(['income', 'expense'])],
            'transactions.*.categoryClientId' => ['nullable', 'uuid'],
            'transactions.*.description' => ['nullable', 'string', 'max:500'],
            'transactions.*.notes' => ['nullable', 'string', 'max:1000'],
            'transactions.*.date' => ['nullable', 'date'],
            'transactions.*.currency' => ['nullable', 'string', 'size:3'],

            'categories' => ['nullable', 'array'],
            'categories.*.clientId' => ['required', 'uuid'],
            'categories.*.updatedAt' => ['required', 'date'],
            'categories.*.deletedAt' => ['nullable', 'date'],
            'categories.*.name' => ['nullable', 'string', 'max:120'],
            'categories.*.type' => ['nullable', Rule::in(['income', 'expense'])],
            'categories.*.budgetCategory' => ['nullable', Rule::in(['needs', 'wants', 'savings', 'investment'])],
            'categories.*.icon' => ['nullable', 'string', 'max:64'],
            'categories.*.color' => ['nullable', 'string', 'max:32'],
            'categories.*.monthlyBudget' => ['nullable', 'numeric', 'min:0'],
            'categories.*.order' => ['nullable', 'integer', 'min:0'],
            'categories.*.isArchived' => ['nullable', 'boolean'],

            'budgets' => ['nullable', 'array'],
            'budgets.*.clientId' => ['required', 'uuid'],
            'budgets.*.updatedAt' => ['required', 'date'],
            'budgets.*.deletedAt' => ['nullable', 'date'],
            'budgets.*.categoryClientId' => ['nullable', 'uuid'],
            'budgets.*.year' => ['nullable', 'integer', 'between:2000,2100'],
            'budgets.*.month' => ['nullable', 'integer', 'between:1,12'],
            'budgets.*.amount' => ['nullable', 'numeric', 'min:0'],
            'budgets.*.isRecurrent' => ['nullable', 'boolean'],

            'recurringTransactions' => ['nullable', 'array'],
            'recurringTransactions.*.clientId' => ['required', 'uuid'],
            'recurringTransactions.*.updatedAt' => ['required', 'date'],
            'recurringTransactions.*.deletedAt' => ['nullable', 'date'],
            'recurringTransactions.*.type' => ['nullable', Rule::in(['income', 'expense'])],
            'recurringTransactions.*.amount' => ['nullable', 'numeric', 'min:0'],
            'recurringTransactions.*.description' => ['nullable', 'string', 'max:500'],
            'recurringTransactions.*.frequency' => ['nullable', Rule::in(['daily', 'weekly', 'biweekly', 'monthly', 'quarterly', 'yearly'])],
            'recurringTransactions.*.nextDueDate' => ['nullable', 'date'],
            'recurringTransactions.*.categoryClientId' => ['nullable', 'uuid'],
            'recurringTransactions.*.isActive' => ['nullable', 'boolean'],

            'savingsGoals' => ['nullable', 'array'],
            'savingsGoals.*.clientId' => ['required', 'uuid'],
            'savingsGoals.*.updatedAt' => ['required', 'date'],
            'savingsGoals.*.deletedAt' => ['nullable', 'date'],
            'savingsGoals.*.name' => ['nullable', 'string', 'max:120'],
            'savingsGoals.*.targetAmount' => ['nullable', 'numeric', 'min:0'],
            'savingsGoals.*.savedAmount' => ['nullable', 'numeric', 'min:0'],
            'savingsGoals.*.deadline' => ['nullable', 'date'],

            'settings' => ['nullable', 'array'],
            'settings.updatedAt' => ['required_with:settings', 'date'],
            'settings.themeMode' => ['nullable', Rule::in(['system', 'light', 'dark'])],
            'settings.accentColor' => ['nullable', 'string', 'max:32'],
            'settings.currency' => ['nullable', 'string', 'max:8'],
            'settings.dailyReminderHour' => ['nullable', 'integer', 'between:0,23'],
            'settings.dailyReminderMinute' => ['nullable', 'integer', 'between:0,59'],
            'settings.dailyReminderEnabled' => ['nullable', 'boolean'],
            'settings.budgetAlertEnabled' => ['nullable', 'boolean'],
            'settings.flexibleStreakDays' => ['nullable', 'integer', 'between:1,7'],
            'settings.cloudSyncEnabled' => ['nullable', 'boolean'],
        ];
    }
}
